apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yaml

configMapGenerator:
  - name: samples-authorization-code-grant
    files:
      - samples/authorization-code-grant/client.json
      - samples/authorization-code-grant/user.json
      - samples/authorization-code-grant/setup-keycloak.sh
  - name: samples-device-authorization-grant
    files:
      - samples/device-authorization-grant/client.json
      - samples/device-authorization-grant/user.json
      - samples/device-authorization-grant/setup-keycloak.sh

patches:
  - path: patches/keycloak-samples-volume.yaml
