apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yaml

configMapGenerator:
  - name: samples-authorization-code-grant
    files:
      - samples/authorization-code-grant/client.json
      - samples/authorization-code-grant/user.json
      - samples/authorization-code-grant/setup-keycloak.sh
  - name: samples-device-authorization-grant
    files:
      - samples/device-authorization-grant/client.json
      - samples/device-authorization-grant/user.json
      - samples/device-authorization-grant/setup-keycloak.sh
  - name: samples-cockroachdb-sso
    files:
      - samples/cockroachdb-sso/client-scope.json
      - samples/cockroachdb-sso/client.json
      - samples/cockroachdb-sso/profile.json
      - samples/cockroachdb-sso/user-buri.json
      - samples/cockroachdb-sso/user-goki.json
      - samples/cockroachdb-sso/setup-keycloak.sh

patches:
  - path: patches/keycloak-samples-volume.yaml
